### ISSUE TITLE
Spend generates a paymentID but returns an error 500

### ISSUE THREAD

**Issue by sweetSneak** [cypher-network/bamboo#49]
<img width="1606" alt="Screenshot_2021-08-27_at_18 09 09" src="https://user-images.githubusercontent.com/42238572/131219116-e62c62fa-4509-47dd-98d3-dec495b3cc1b.png">

**Comment by sanastasiou** [comment]
Fixed by https://github.com/cypher-network/bamboo/pull/46

**Comment by pingpongsneak** [comment]
Fixed #46
