### ISSUE TITLE
Receive by paymentID throws error

### ISSUE THREAD

**Issue by sweetSneak** [cypher-network/bamboo#50]
Upon a user receiving a payment by `paymentID` returns an ERROR with `failed to find a transaction with paymentID: <paymentID>`

![unknown](https://user-images.githubusercontent.com/42238572/131219207-69621952-7796-4438-a898-0dc24b766f26.png)

Although the paymentID is generated by the wallet the above causes the user to not be able to receive with the command. 
Although the payment is sent if a recover is done and/or sometime has passed.

**Comment by pingpongsneak** [comment]
I'll keep an eye on this as this has been working when tested with some users.
