### ISSUE TITLE
Close wallet when another instance of wallet already runs

### ISSUE THREAD

**Issue by sanastasiou** [cypher-network/bamboo#51]
{"@t":"2021-08-28T11:08:55.8738882Z","@mt":"Starting wallet"}
{"@t":"2021-08-28T11:08:55.9380441Z","@mt":"Version: 0.0.26.0"}
{"@t":"2021-08-28T11:08:56.3604287Z","@mt":"Now listening on: {address}","address":"http://localhost:8007","SourceContext":"Microsoft.Hosting.Lifetime"}
{"@t":"2021-08-28T11:08:56.3711609Z","@mt":"Application started. Press Ctrl+C to shut down.","SourceContext":"Microsoft.Hosting.Lifetime"}
{"@t":"2021-08-28T11:08:56.3712938Z","@mt":"Hosting environment: {envName}","envName":"Production","SourceContext":"Microsoft.Hosting.Lifetime"}
{"@t":"2021-08-28T11:08:56.3713193Z","@mt":"Content root path: {contentRoot}","contentRoot":"/root/bamboo/publish","SourceContext":"Microsoft.Hosting.Lifetime"}
{"@t":"2021-08-28T11:10:43.6329901Z","@mt":"Result: {@Content}\n StatusCode: {@StatusCode}","@l":"Error","Content":{"MoveNextAction":"System.Action","Result":"{\"type\":\"https://tools.ietf.org/html/rfc7231#section-6.5.4\",\">{"@t":"2021-08-28T11:10:43.6638819Z","@mt":"Result: {@Content}\n StatusCode: {@StatusCode}","@l":"Error","Content":{"MoveNextAction":"System.Action","Result":"{\"type\":\"https://tools.ietf.org/html/rfc7231#section-6.5.4\",\">{"@t":"2021-08-28T11:11:44.6943689Z","@mt":"Result: {@Content}\n StatusCode: {@StatusCode}","@l":"Error","Content":{"MoveNextAction":"System.Action","Result":"{\"type\":\"https://tools.ietf.org/html/rfc7231#section-6.5.4\",\">{"@t":"2021-08-28T11:11:44.7340203Z","@mt":"Result: {@Content}\n StatusCode: {@StatusCode}","@l":"Error","Content":{"MoveNextAction":"System.Action","Result":"{\"type\":\"https://tools.ietf.org/html/rfc7231#section-6.5.4\",\">{"@t":"2021-08-28T11:15:15.6972646Z","@mt":"Result: {@Content}\n StatusCode: {@StatusCode}","@l":"Error","Content":{"MoveNextAction":"System.Action","Result":"{\"type\":\"https://tools.ietf.org/html/rfc7231#section-6.5.4\",\">{"@t":"2021-08-28T11:15:16.6990262Z","@mt":"Result: {@Content}\n StatusCode: {@StatusCode}","@l":"Error","Content":{"MoveNextAction":"System.Action","Result":"{\"type\":\"https://tools.ietf.org/html/rfc7231#section-6.5.4\",\">{"@t":"2021-08-28T12:31:57.0334708Z","@mt":"Starting wallet"}
{"@t":"2021-08-28T12:31:57.0921506Z","@mt":"Version: 0.0.26.0"}
{"@t":"2021-08-28T12:31:57.4936908Z","@mt":"Unable to start Kestrel.","@l":"Fatal","@x":"System.IO.IOException: Failed to bind to address http://127.0.0.1:8007: address already in use.\n ---> Microsoft.AspNetCore.Connections.>{"@t":"2021-08-28T12:31:57.5600857Z","@mt":"Host terminated unexpectedly","@l":"Fatal","@x":"System.IO.IOException: Failed to bind to address http://127.0.0.1:8007: address already in use.\n ---> Microsoft.AspNetCore.Connecti>{"@t":"2021-08-28T12:36:51.4000636Z","@mt":"Starting wallet"}
{"@t":"2021-08-28T12:36:51.4569296Z","@mt":"Version: 0.0.26.0"}
{"@t":"2021-08-28T12:36:51.8662385Z","@mt":"Unable to start Kestrel.","@l":"Fatal","@x":"System.IO.IOException: Failed to bind to address http://127.0.0.1:8007: address already in use.\n ---> Microsoft.AspNetCore.Connections.>{"@t":"2021-08-28T12:36:51.9327034Z","@mt":"Host terminated unexpectedly","@l":"Fatal","@x":"System.IO.IOException: Failed to bind to address http://127.0.0.1:8007: address already in use.\n ---> Microsoft.AspNetCore.Connecti>{"@t":"2021-08-28T12:39:04.6645619Z","@mt":"Starting wallet"}
{"@t":"2021-08-28T12:39:04.7275195Z","@mt":"Version: 0.0.26.0"}
{"@t":"2021-08-28T12:39:05.1600010Z","@mt":"Unable to start Kestrel.","@l":"Fatal","@x":"System.IO.IOException: Failed to bind to address http://127.0.0.1:8007: address already in use.\n ---> Microsoft.AspNetCore.Connections.>{"@t":"2021-08-28T12:39:05.2249850Z","@mt":"Host terminated unexpectedly","@l":"Fatal","@x":"System.IO.IOException: Failed to bind to address http://127.0.0.1:8007: address already in use.\n ---> Microsoft.AspNetCore.Connecti>{"@t":"2021-08-28T12:45:34.1942046Z","@mt":"Starting wallet"}
{"@t":"2021-08-28T12:45:34.2599196Z","@mt":"Version: 0.0.26.0"}
{"@t":"2021-08-28T12:45:34.6961675Z","@mt":"Unable to start Kestrel.","@l":"Fatal","@x":"System.IO.IOException: Failed to bind to address http://127.0.0.1:8007: address already in use.\n ---> Microsoft.AspNetCore.Connections.>{"@t":"2021-08-28T12:45:34.7651785Z","@mt":"Host terminated unexpectedly","@l":"Fatal","@x":"System.IO.IOException: Failed to bind to address http://127.0.0.1:8007: address already in use.\n ---> Microsoft.AspNetCore.Connecti>{"@t":"2021-08-28T12:47:43.2591425Z","@mt":"Starting wallet"}
{"@t":"2021-08-28T12:47:43.3179423Z","@mt":"Version: 0.0.26.0"}
{"@t":"2021-08-28T12:47:43.7136617Z","@mt":"Unable to start Kestrel.","@l":"Fatal","@x":"System.IO.IOException: Failed to bind to address http://127.0.0.1:8007: address already in use.\n ---> Microsoft.AspNetCore.Connections.>{"@t":"2021-08-28T12:47:43.7855069Z","@mt":"Host terminated unexpectedly","@l":"Fatal","@x":"System.IO.IOException: Failed to bind to address http://127.0.0.1:8007: address already in use.\n ---> Microsoft.AspNetCore.Connecti>{"@t":"2021-08-28T12:49:16.5227006Z","@mt":"Starting wallet"}
{"@t":"2021-08-28T12:49:16.5872206Z","@mt":"Version: 0.0.26.0"}
{"@t":"2021-08-28T12:49:16.9698637Z","@mt":"Unable to start Kestrel.","@l":"Fatal","@x":"System.IO.IOException: Failed to bind to address http://127.0.0.1:8007: address already in use.\n ---> Microsoft.AspNetCore.Connections.>{"@t":"2021-08-28T12:49:17.0339772Z","@mt":"Host terminated unexpectedly","@l":"Fatal","@x":"System.IO.IOException: Failed to bind to address http://127.0.0.1:8007: address already in use.\n ---> Microsoft.AspNetCore.Connecti>{"@t":"2021-08-28T12:49:20.7539892Z","@mt":"Starting wallet"}
{"@t":"2021-08-28T12:49:20.8149796Z","@mt":"Version: 0.0.26.0"}
{"@t":"2021-08-28T12:49:21.2141601Z","@mt":"Unable to start Kestrel.","@l":"Fatal","@x":"System.IO.IOException: Failed to bind to address http://127.0.0.1:8007: address already in use.\n ---> Microsoft.AspNetCore.Connections.>{"@t":"2021-08-28T12:49:21.2761541Z","@mt":"Host terminated unexpectedly","@l":"Fatal","@x":"System.IO.IOException: Failed to bind to address http://127.0.0.1:8007: address already in use.\n ---> Microsoft.AspNetCore.Connecti>{"@t":"2021-08-28T12:49:25.1934954Z","@mt":"Starting wallet"}
{"@t":"2021-08-28T12:49:25.2506140Z","@mt":"Version: 0.0.26.0"}
{"@t":"2021-08-28T12:49:25.6542677Z","@mt":"Unable to start Kestrel.","@l":"Fatal","@x":"System.IO.IOException: Failed to bind to address http://127.0.0.1:8007: address already in use.\n ---> Microsoft.AspNetCore.Connections.>{"@t":"2021-08-28T12:49:25.7205956Z","@mt":"Host terminated unexpectedly","@l":"Fatal","@x":"System.IO.IOException: Failed to bind to address http://127.0.0.1:8007: address already in use.\n ---> Microsoft.AspNetCore.Connecti>{"@t":"2021-08-28T12:53:28.5522302Z","@mt":"Starting wallet"}
{"@t":"2021-08-28T12:53:28.6117655Z","@mt":"Version: 0.0.26.0"}
{"@t":"2021-08-28T12:53:29.0162689Z","@mt":"Unable to start Kestrel.","@l":"Fatal","@x":"System.IO.IOException: Failed to bind to address http://127.0.0.1:8007: address already in use.\n ---> Microsoft.AspNetCore.Connections.>{"@t":"2021-08-28T12:53:29.0919414Z","@mt":"Host terminated unexpectedly","@l":"Fatal","@x":"System.IO.IOException: Failed to bind to address http://127.0.0.1:8007: address already in use.\n ---> Microsoft.AspNetCore.Connecti>{"@t":"2021-08-28T12:56:15.9072583Z","@mt":"Starting wallet"}
{"@t":"2021-08-28T12:56:15.9640896Z","@mt":"Version: 0.0.26.0"}
{"@t":"2021-08-28T12:56:16.3684340Z","@mt":"Unable to start Kestrel.","@l":"Fatal","@x":"System.IO.IOException: Failed to bind to address http://127.0.0.1:8007: address already in use.\n ---> Microsoft.AspNetCore.Connections.>{"@t":"2021-08-28T12:56:16.4329468Z","@mt":"Host terminated unexpectedly","@l":"Fatal","@x":"System.IO.IOException: Failed to bind to address http://127.0.0.1:8007: address already in use.\n ---> Microsoft.AspNetCore.Connecti>{"@t":"2021-08-28T13:18:13.5714906Z","@mt":"Starting wallet"}
{"@t":"2021-08-28T13:18:13.6313106Z","@mt":"Version: 0.0.26.0"}
{"@t":"2021-08-28T13:18:14.0398631Z","@mt":"Now listening on: {address}","address":"http://localhost:8007","SourceContext":"Microsoft.Hosting.Lifetime"}
{"@t":"2021-08-28T13:18:14.0496171Z","@mt":"Application started. Press Ctrl+C to shut down.","SourceContext":"Microsoft.Hosting.Lifetime"}
{"@t":"2021-08-28T13:18:14.0497235Z","@mt":"Hosting environment: {envName}","envName":"Production","SourceContext":"Microsoft.Hosting.Lifetime"}
{"@t":"2021-08-28T13:18:14.0497488Z","@mt":"Content root path: {contentRoot}","contentRoot":"/root/bamboo/publish","SourceContext":"Microsoft.Hosting.Lifetime"}
{"@t":"2021-08-28T13:20:32.1782194Z","@mt":"Result: {@Content}\n StatusCode: {@StatusCode}","@l":"Error","Content":{"Result":"{\"type\":\"https://tools.ietf.org/html/rfc7231#section-6.5.4\",\"title\":\"Not Found\",\"status\":>{"@t":"2021-08-28T13:20:32.8047817Z","@mt":"Result: {@Content}\n StatusCode: {@StatusCode}","@l":"Error","Content":{"Result":"{\"type\":\"https://tools.ietf.org/html/rfc7231#section-6.5.4\",\"title\":\"Not Found\",\"status\":>{"@t":"2021-08-28T13:21:34.4955709Z","@mt":"Result: {@Content}\n StatusCode: {@StatusCode}","@l":"Error","Content":{"Result":"{\"type\":\"https://tools.ietf.org/html/rfc7231#section-6.5.4\",\"title\":\"Not Found\",\"status\":>{"@t":"2021-08-28T13:21:34.5083874Z","@mt":"Result: {@Content}\n StatusCode: {@StatusCode}","@l":"Error","Content":{"Result":"{\"type\":\"https://tools.ietf.org/html/rfc7231#section-6.5.4\",\"title\":\"Not Found\",\"status\":>{"@t":"2021-08-28T13:21:35.3148828Z","@mt":"Result: {@Content}\n StatusCode: {@StatusCode}","@l":"Error","Content":{"MoveNextAction":"System.Action","Result":"{\"type\":\"https://tools.ietf.org/html/rfc7231#section-6.5.4\",\">{"@t":"2021-08-28T13:24:34.2944083Z","@mt":"Result: {@Content}\n StatusCode: {@StatusCode}","@l":"Error","Content":{"Result":"{\"type\":\"https://tools.ietf.org/html/rfc7231#section-6.5.4\",\"title\":\"Not Found\",\"status\":>{"@t":"2021-08-28T13:24:34.3913759Z","@mt":"Result: {@Content}\n StatusCode: {@StatusCode}","@l":"Error","Content":{"Result":"{\"type\":\"https://tools.ietf.org/html/rfc7231#section-6.5.4\",\"title\":\"Not Found\",\"status\":>{"@t":"2021-08-28T13:24:34.4722008Z","@mt":"Result: {@Content}\n StatusCode: {@StatusCode}","@l":"Error","Content":{"Result":"{\"type\":\"https://tools.ietf.org/html/rfc7231#section-6.5.4\",\"title\":\"Not Found\",\"status\":>{"@t":"2021-08-28T13:28:50.3258277Z","@mt":"Result: {@Content}\n StatusCode: {@StatusCode}","@l":"Error","Content":{"Result":"500","Id":9,"Exception":null,"Status":"RanToCompletion","IsCanceled":false,"IsCompleted":true,"IsCo>{"@t":"2021-08-28T13:31:28.2981095Z","@mt":"Result: {@Content}\n StatusCode: {@StatusCode}","@l":"Error","Content":{"MoveNextAction":"System.Action","Result":"{\"type\":\"https://tools.ietf.org/html/rfc7231#section-6.5.4\",\">{"@t":"2021-08-28T13:31:28.3028898Z","@mt":"Result: {@Content}\n StatusCode: {@StatusCode}","@l":"Error","Content":{"Result":"{\"type\":\"https://tools.ietf.org/html/rfc7231#section-6.5.4\",\"title\":\"Not Found\",\"status\":>{"@t":"2021-08-28T13:31:29.2989629Z","@mt":"Result: {@Content}\n StatusCode: {@StatusCode}","@l":"Error","Content":{"MoveNextAction":"System.Action","Result":"{\"type\":\"https://tools.ietf.org/html/rfc7231#section-6.5.4\",\">{"@t":"2021-08-28T13:35:29.5759480Z","@mt":"Result: {@Content}\n StatusCode: {@StatusCode}","@l":"Error","Content":{"Result":"500","Id":13,"Exception":null,"Status":"RanToCompletion","IsCanceled":false,"IsCompleted":true,"IsC>{"@t":"2021-08-28T13:37:35.7781695Z","@mt":"Result: {@Content}\n StatusCode: {@StatusCode}","@l":"Error","Content":{"MoveNextAction":"System.Action","Result":"{\"type\":\"https://tools.ietf.org/html/rfc7231#section-6.5.4\",\">{"@t":"2021-08-28T13:37:42.6981830Z","@mt":"Application is shutting down...","SourceContext":"Microsoft.Hosting.Lifetime"}
{"@t":"2021-08-28T13:37:48.7545910Z","@mt":"Starting wallet"}
{"@t":"2021-08-28T13:37:48.8141144Z","@mt":"Version: 0.0.26.0"}
{"@t":"2021-08-28T13:37:49.2047782Z","@mt":"Now listening on: {address}","address":"http://localhost:8007","SourceContext":"Microsoft.Hosting.Lifetime"}
{"@t":"2021-08-28T13:37:49.2167972Z","@mt":"Application started. Press Ctrl+C to shut down.","SourceContext":"Microsoft.Hosting.Lifetime"}
{"@t":"2021-08-28T13:37:49.2169380Z","@mt":"Hosting environment: {envName}","envName":"Production","SourceContext":"Microsoft.Hosting.Lifetime"}
{"@t":"2021-08-28T13:37:49.2169705Z","@mt":"Content root path: {contentRoot}","contentRoot":"/root/bamboo/publish","SourceContext":"Microsoft.Hosting.Lifetime"}
{"@t":"2021-08-28T13:39:37.8829408Z","@mt":"Result: {@Content}\n StatusCode: {@StatusCode}","@l":"Error","Content":{"MoveNextAction":"System.Action","Result":"{\"type\":\"https://tools.ietf.org/html/rfc7231#section-6.5.4\",\">{"@t":"2021-08-28T13:39:37.8859285Z","@mt":"Result: {@Content}\n StatusCode: {@StatusCode}","@l":"Error","Content":{"Result":"{\"type\":\"https://tools.ietf.org/html/rfc7231#section-6.5.4\",\"title\":\"Not Found\",\"status\":>{"@t":"2021-08-28T13:39:37.9527196Z","@mt":"Result: {@Content}\n StatusCode: {@StatusCode}","@l":"Error","Content":{"MoveNextAction":"System.Action","Result":"{\"type\":\"https://tools.ietf.org/html/rfc7231#section-6.5.4\",\">{"@t":"2021-08-28T13:40:53.4780278Z","@mt":"Application is shutting down...","SourceContext":"Microsoft.Hosting.Lifetime"}
{"@t":"2021-08-28T13:42:31.4765387Z","@mt":"Starting wallet"}
{"@t":"2021-08-28T13:42:31.5347594Z","@mt":"Version: 0.0.26.0"}
{"@t":"2021-08-28T13:42:31.9020660Z","@mt":"Now listening on: {address}","address":"http://localhost:8007","SourceContext":"Microsoft.Hosting.Lifetime"}
{"@t":"2021-08-28T13:42:31.9132043Z","@mt":"Application started. Press Ctrl+C to shut down.","SourceContext":"Microsoft.Hosting.Lifetime"}
{"@t":"2021-08-28T13:42:31.9133198Z","@mt":"Hosting environment: {envName}","envName":"Production","SourceContext":"Microsoft.Hosting.Lifetime"}
{"@t":"2021-08-28T13:42:31.9133576Z","@mt":"Content root path: {contentRoot}","contentRoot":"/root/bamboo/publish","SourceContext":"Microsoft.Hosting.Lifetime"}
{"@t":"2021-08-28T13:43:42.8176275Z","@mt":"Result: {@Content}\n StatusCode: {@StatusCode}","@l":"Error","Content":{"Result":"500","Id":1,"Exception":null,"Status":"RanToCompletion","IsCanceled":false,"IsCompleted":true,"IsCo>{"@t":"2021-08-28T13:44:17.4066483Z","@mt":"Result: {@Content}\n StatusCode: {@StatusCode}","@l":"Error","Content":{"Result":"500","Id":2,"Exception":null,"Status":"RanToCompletion","IsCanceled":false,"IsCompleted":true,"IsCo>{"@t":"2021-08-28T13:46:29.8854260Z","@mt":"Result: {@Content}\n StatusCode: {@StatusCode}","@l":"Error","Content":{"MoveNextAction":"System.Action","Result":"{\"type\":\"https://tools.ietf.org/html/rfc7231#section-6.5.4\",\">{"@t":"2021-08-28T13:46:30.8107169Z","@mt":"Result: {@Content}\n StatusCode: {@StatusCode}","@l":"Error","Content":{"MoveNextAction":"System.Action","Result":"{\"type\":\"https://tools.ietf.org/html/rfc7231#section-6.5.4\",\">{"@t":"2021-08-28T13:47:52.9291956Z","@mt":"Result: {@Content}\n StatusCode: {@StatusCode}","@l":"Error","Content":{"MoveNextAction":"System.Action","Result":"{\"type\":\"https://tools.ietf.org/html/rfc7231#section-6.5.4\",\">{"@t":"2021-08-28T13:47:52.9368736Z","@mt":"Result: {@Content}\n StatusCode: {@StatusCode}","@l":"Error","Content":{"Result":"{\"type\":\"https://tools.ietf.org/html/rfc7231#section-6.5.4\",\"title\":\"Not Found\",\"status\":>{"@t":"2021-08-28T13:47:53.9554313Z","@mt":"Result: {@Content}\n StatusCode: {@StatusCode}","@l":"Error","Content":{"MoveNextAction":"System.Action","Result":"{\"type\":\"https://tools.ietf.org/html/rfc7231#section-6.5.4\",\">{"@t":"2021-08-28T13:51:25.9912245Z","@mt":"Application is shutting down...","SourceContext":"Microsoft.Hosting.Lifetime"}
{"@t":"2021-08-28T13:52:48.1803887Z","@mt":"Starting wallet"}
{"@t":"2021-08-28T13:52:48.2378158Z","@mt":"Version: 0.0.26.0"}
{"@t":"2021-08-28T13:52:48.6444010Z","@mt":"Now listening on: {address}","address":"http://localhost:8007","SourceContext":"Microsoft.Hosting.Lifetime"}
{"@t":"2021-08-28T13:52:48.6568134Z","@mt":"Application started. Press Ctrl+C to shut down.","SourceContext":"Microsoft.Hosting.Lifetime"}
{"@t":"2021-08-28T13:52:48.6569493Z","@mt":"Hosting environment: {envName}","envName":"Production","SourceContext":"Microsoft.Hosting.Lifetime"}
{"@t":"2021-08-28T13:52:48.6569760Z","@mt":"Content root path: {contentRoot}","contentRoot":"/root/bamboo/publish","SourceContext":"Microsoft.Hosting.Lifetime"}
{"@t":"2021-08-28T13:53:45.3292967Z","@mt":"Application is shutting down...","SourceContext":"Microsoft.Hosting.Lifetime"}

**Comment by pingpongsneak** [comment]
Fixed: save previous process id.
